import { Sparkles, ThumbsUp, ThumbsDown } from "lucide-react";

interface AiReviewSummaryProps {
  productName: string;
}

export function AiReviewSummary({ productName }: AiReviewSummaryProps) {
  // In a real app, this data would come from the backend, generated by an LLM based on actual reviews.
  const summary = {
    overall: `Customers highly recommend the ${productName} for its exceptional quality and value. Many users noted immediate positive results and praised the durable packaging.`,
    pros: ["Excellent build quality", "Great value for money", "Fast shipping", "Exactly as described"],
    cons: ["Slightly larger than expected", "Instructions could be clearer"]
  };

  return (
    <div className="rounded-xl border border-primary/20 bg-gradient-to-br from-primary/5 to-background p-5 shadow-sm relative overflow-hidden">
      {/* AI Glow effect */}
      <div className="absolute -top-10 -right-10 w-32 h-32 bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      
      <div className="relative z-10">
        <div className="flex items-center gap-2 mb-4">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary shadow-inner">
            <Sparkles size={16} className="text-primary" />
          </div>
          <h3 className="font-bold text-lg">AI Review Summary</h3>
          <span className="ml-2 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary uppercase tracking-wider">Beta</span>
        </div>

        <p className="text-sm text-foreground/90 leading-relaxed mb-5">
          {summary.overall}
        </p>

        <div className="grid md:grid-cols-2 gap-4">
          <div className="rounded-lg bg-background/50 border p-3 backdrop-blur-sm">
            <div className="flex items-center gap-1.5 mb-2 text-sm font-semibold text-[var(--success)]">
              <ThumbsUp size={14} /> Top Pros
            </div>
            <ul className="space-y-1">
              {summary.pros.map((pro, idx) => (
                <li key={idx} className="text-xs text-muted-foreground flex items-start gap-1.5">
                  <span className="text-[var(--success)] mt-0.5">•</span> {pro}
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-lg bg-background/50 border p-3 backdrop-blur-sm">
            <div className="flex items-center gap-1.5 mb-2 text-sm font-semibold text-destructive">
              <ThumbsDown size={14} /> Top Cons
            </div>
            <ul className="space-y-1">
              {summary.cons.map((con, idx) => (
                <li key={idx} className="text-xs text-muted-foreground flex items-start gap-1.5">
                  <span className="text-destructive mt-0.5">•</span> {con}
                </li>
              ))}
            </ul>
          </div>
        </div>
        
        <div className="mt-4 text-[10px] text-muted-foreground text-center">
          Summary generated by AI based on customer reviews. May contain inaccuracies.
        </div>
      </div>
    </div>
  );
}
