/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopWishlistRouteImport } from './routes/_shop/wishlist'
import { Route as ShopSearchRouteImport } from './routes/_shop/search'
import { Route as ShopRegisterRouteImport } from './routes/_shop/register'
import { Route as ShopProfileRouteImport } from './routes/_shop/profile'
import { Route as ShopOrdersRouteImport } from './routes/_shop/orders'
import { Route as ShopLoginRouteImport } from './routes/_shop/login'
import { Route as ShopDiscoverRouteImport } from './routes/_shop/discover'
import { Route as ShopCheckoutRouteImport } from './routes/_shop/checkout'
import { Route as ShopCartRouteImport } from './routes/_shop/cart'
import { Route as ShopPSlugRouteImport } from './routes/_shop/p.$slug'
import { Route as ShopCSlugRouteImport } from './routes/_shop/c.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRegisterRoute = ShopRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopDiscoverRoute = ShopDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPSlugRoute = ShopPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCSlugRoute = ShopCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/discover': typeof ShopDiscoverRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/profile': typeof ShopProfileRoute
  '/register': typeof ShopRegisterRoute
  '/search': typeof ShopSearchRoute
  '/wishlist': typeof ShopWishlistRoute
  '/c/$slug': typeof ShopCSlugRoute
  '/p/$slug': typeof ShopPSlugRoute
}
export interface FileRoutesByTo {
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/discover': typeof ShopDiscoverRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/profile': typeof ShopProfileRoute
  '/register': typeof ShopRegisterRoute
  '/search': typeof ShopSearchRoute
  '/wishlist': typeof ShopWishlistRoute
  '/': typeof ShopIndexRoute
  '/c/$slug': typeof ShopCSlugRoute
  '/p/$slug': typeof ShopPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/discover': typeof ShopDiscoverRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/profile': typeof ShopProfileRoute
  '/_shop/register': typeof ShopRegisterRoute
  '/_shop/search': typeof ShopSearchRoute
  '/_shop/wishlist': typeof ShopWishlistRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/c/$slug': typeof ShopCSlugRoute
  '/_shop/p/$slug': typeof ShopPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/discover'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/search'
    | '/wishlist'
    | '/c/$slug'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/checkout'
    | '/discover'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/search'
    | '/wishlist'
    | '/'
    | '/c/$slug'
    | '/p/$slug'
  id:
    | '__root__'
    | '/_shop'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/discover'
    | '/_shop/login'
    | '/_shop/orders'
    | '/_shop/profile'
    | '/_shop/register'
    | '/_shop/search'
    | '/_shop/wishlist'
    | '/_shop/'
    | '/_shop/c/$slug'
    | '/_shop/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/wishlist': {
      id: '/_shop/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/search': {
      id: '/_shop/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/register': {
      id: '/_shop/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof ShopRegisterRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/profile': {
      id: '/_shop/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/discover': {
      id: '/_shop/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof ShopDiscoverRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/p/$slug': {
      id: '/_shop/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof ShopPSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/c/$slug': {
      id: '/_shop/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof ShopCSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopDiscoverRoute: typeof ShopDiscoverRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopRegisterRoute: typeof ShopRegisterRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCSlugRoute: typeof ShopCSlugRoute
  ShopPSlugRoute: typeof ShopPSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopDiscoverRoute: ShopDiscoverRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopRegisterRoute: ShopRegisterRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCSlugRoute: ShopCSlugRoute,
  ShopPSlugRoute: ShopPSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
